### ISSUE TITLE
Missing escape for role-session-name for OIDC & temporary credentials expiration

### ISSUE THREAD

**Issue by ad-m-ss** [CircleCI-Public/aws-cli-orb#104]
I use orb:

```
            - aws-cli/setup:
                aws-region: << parameters.aws-region >>
                role-arn: << parameters.aws-role-arn >>
```

I receive in logs:

```
#!/bin/bash -eo pipefail
PARAM_ROLE_SESSION_NAME=$(eval echo "${PARAM_ROLE_SESSION_NAME}")

# shellcheck disable=SC2086,SC2034
read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN <<<"$(aws sts assume-role-with-web-identity \
    --role-arn ${PARAM_AWS_CLI_ROLE_ARN} \
    --role-session-name ${PARAM_ROLE_SESSION_NAME} \
    --web-identity-token ${CIRCLE_OIDC_TOKEN} \
    --duration-seconds ${PARAM_SESSION_DURATION} \
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
    --output text)"
{
    echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
    echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
    echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
} >>"$BASH_ENV"


usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: on, dev-adam, chart
```

I think that steps should fail when it failed to obtain token (it fails silently on CI). Also there is missing escape around "PARAM_ROLE_SESSION_NAME", so my job with space fails.

In addiction, I suggest you to:
* read https://ben11kehoe.medium.com/never-put-aws-temporary-credentials-in-env-vars-or-credentials-files-theres-a-better-way-25ec45b4d73e or about `AWS_WEB_IDENTITY_TOKEN_FILE` 
* stop exporting temporary credentials

**Comment by brivu** [comment]
Hey @ad-m-ss, 

Thanks for your contribution. `role-session-name` is actually required and can not be an empty string. I'll go ahead and add some validation for it. 

In terms the article you sent, it suggests using the `config` file to create new profiles instead of `credentials`. While this is great, the `assume-role-with-web-identity` eliminates static credentials entirely and uses the `CIRCLE_OIDC_TOKEN` to create a profile with temporary keys. There is no default profile out of the box so you can't assume a role from a `source-profile`.

The good news is we have a command called `role-arn-setup` that does just that. You're able to pass in a `role-arn` and and `source-profile` that lets you create a new profile in the `config` file. This assumes that you run the `setup` command first to configure a default profile with your static credentials. 

I hope that makes sense. Let me know what you think!

Best, 
Brian

**Comment by ad-m-ss** [comment]
> Thanks for your contribution. `role-session-name` is actually required and can not be an empty string. I'll go ahead and add some validation for it.

By default it have value `${CIRCLE_JOB}`, so it does have value in my cases. The issue is that my value have probably spaces, so it fails on validation. Notice at the end of output:

```
Unknown options: on, dev-adam, chart
```

I believe this is due to the presence of spaces somewhere in the middle of the default parameters.

> uses the CIRCLE_OIDC_TOKEN to create a profile with temporary keys.

I think this is risky, because it might fails when temporary keys expires or become invalided for some other reason. Article describes that application which consume temporary keys should be able to rotate it:

> code that uses temporary credentials should be able to refresh those credentials. 

Code which exports temporary keys does not follow this rule. I am aware that documentation of AWS STS does not explain that well ( https://github.com/awsdocs/iam-user-guide/issues/249 ). 

You might use `AWS.TokenFileWebIdentityCredentials` to enable application to use temporary keys and enable to refresh those credentials by application. This is the mechanism used in AWS EKS for IRSA, so it is a stable and well-established solution ( https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ ) supported in all modern AWS SDK. It requires something like:

```bash
TOKEN_FILE=$(mktemp)
echo "CIRCLE_OIDC_TOKEN" > "$TOKEN_FILE"
{
    echo "export AWS_WEB_IDENTITY_TOKEN_FILE=\"${TOKEN_FILE}\""
    echo "export AWS_ROLE_ARN=\"${PARAM_AWS_CLI_ROLE_ARN}\""
} >>"$BASH_ENV"
```

Alternatively you might use `AWS.ProcessCredentials` to create profile which is able to retrieve fresh temporary keys.

**Comment by pavelkucera** [comment]
Hi,

I'm running into the same issue, my Job Name contains spaces and then it is not passed to AWS CLI properly. I believe that a fix would be to pass env variables using double quotes to prevent globbing and word splitting. Should I send a PR with that?

**Comment by brivu** [comment]
Hey @pavelkucera, 

Can you show me an example config of what you mean so I can check it out?

Best, 
Brian

**Comment by pavelkucera** [comment]
Hi @brivu, the gist of the config:
```
jobs:
  aws-job:
    steps:
      - aws-cli/setup:
          role-arn: ...

workflows:
  deploy:
    jobs:
      - job-with-spaces:
          name: Name with spaces
```

As for the double quoting, I think it needs to happen in shell, specifically in [assume-role-with-web-identity.sh:12](https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/scripts/assume-role-with-web-identity.sh#L12) I would add double quotes around `${PARAM_ROLE_SESSION_NAME}` Would that make sense?

**Comment by brivu** [comment]
Yes, thank you!

**Comment by jtheuer** [comment]
I ran into the same issue and want to point out another important issue connected to this: The script didn't fail for me so my deployment continued to run and I received confusing aws authentication errors further down the build pipeline.

Can you please add validation that the env vars where correctly set and fail your script (orb) if not? I believe working with correct exit codes is a common best practice for shell (and CI) jobs.

**Comment by jtheuer** [comment]
Hi Brian, thanks for reaching out and taking care for this. I currently have no capacity to provide a full PR to vendors. However, setting a job name with a space should be sufficient to reproduce both issues.
Let me know when you have a fix deployed, I'm eager to try the new version.
