### ISSUE TITLE
Silient failure for missing context for "aws sts assume-role-with-web-identity"

### ISSUE THREAD

**Issue by ad-m-ss** [CircleCI-Public/aws-cli-orb#109]
I miss to specify context to enable OIDC token in my workflows. Steps to setup temporary credentials pass silently:

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/99484706/167054139-8b2922fc-122e-4fd0-a220-e3013b888bd8.png">

I would like receive error in that step to easier identify the root cause of failure.

**Comment by jfirebaugh** [comment]
Similarly, if awscli is not installed, the `aws-cli/assume-role-with-web-identity` still "succeeds", despite failing internally with an "aws: command not found" error. Expected behavior is that the step fails, so that it's easy to identify the issue.

**Comment by duffn** [comment]
The original post here seems to have been fixed with https://github.com/CircleCI-Public/aws-cli-orb/issues/106. Your screenshot shows the code prior to this PR.
