### ISSUE TITLE
aws-cli/setup fails in shells that disallow unset variables

### ISSUE THREAD

**Issue by lewalt000** [CircleCI-Public/aws-cli-orb#119]
9/2/2022 update - see https://github.com/CircleCI-Public/aws-cli-orb/issues/119#issuecomment-1235730571 for updated issue description. 

## What would you like to be added

It would be very useful to add `working_directory` as a configuration parameter to the `aws-cli/setup` command. Has this option been considered?

## Why is this needed

Some jobs set a default `working_directory` for the entire job, which also effects orb installs. I've observed this orb fail to install with error `environment: line 29: $1: unbound variable`, which is fixed by removing the `working_directory` for the entire job. Therefore, it would be very useful to be able to set a different `working_directory` for the `aws-cli` orb specifically, so the rest of a job can use a different default value.

As an example, the cypress orb has this feature: https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#custom-directory.

I'm also open to submitting a PR if any project maintainer can comment on this idea. Thank you!

**Comment by brivu** [comment]
Hey @lewalt000, 

I'm still a little unclear what this new parameter would used for. Can you give me a sample config that causes your job to fail?

Let me know and thank you for your contribution!

Best, 
Brian

**Comment by lewalt000** [comment]
@brivu thank you for your reply. While working on a minimal reproducible config, I've realized the install issue is not related to working directory, but rather running the orb in a shell environment with: `/bin/bash -o nounset`. I will update the issue title accordingly.

This causes the error:

```
Installing AWS CLI v2
Linux ee27d96d1f78 5.13.0-1023-aws #25~20.04.1-Ubuntu SMP Mon Apr 25 19:28:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
environment: line 29: $1: unbound variable

Exited with code exit status 127
CircleCI received exit code 127
```

In my environment, many workflows have `- o nounset` as a shell default. Would it make sense to patch the install script so there isn't an unset variable?

Here is the config to reproduce:
```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    shell: /bin/bash -o nounset
    docker:
      - image: cimg/base:2022.08
    steps:
      - aws-cli/setup:
          profile-name: my-profile 
```
