### ISSUE TITLE
Don't check for sudo if already running as root

### ISSUE THREAD

**Issue by DWSR** [CircleCI-Public/aws-cli-orb#12]
### Orb version

`aws-s3@1.0.0`

### What happened

The `Install AWS CLI` script checks for the presence of `sudo` in PATH, even if already running as root.

### Expected behavior

The script should skip checking for sudo if already running as `root`.

**Comment by iynere** [comment]
@DWSR can you try the latest version of the `s3` orb (1.0.9) & let us know if this is still an issue ?
