### ISSUE TITLE
Use orb 3.4.1 install command with parameters  override-installed: true  and/or version: latest

### ISSUE THREAD

**Issue by serg-sva** [CircleCI-Public/aws-cli-orb#127]
When use this orb on the ubuntu with installed AWS CLI I get this error:
_/usr/local/bin/aws
Uninstalling aws-cli/2.4.6 Python/3.8.8 Linux/5.11.0-1022-aws exe/x86_64.ubuntu.20 prompt/off
Installing AWS CLI v2
Linux ip-172-28-59-4 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[awscliv2.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of awscliv2.zip or
        awscliv2.zip.zip, and cannot find awscliv2.zip.ZIP, period._

**Comment by brivu** [comment]
Hey @serg-sva, 

I've just tested this on various versions of the orb and several different  ubuntu based executors. It all seems to be working fine for me. If this is still an issue, please feel free to reopen and provide me with the specific executor that's causing this failure. 

Thank you! 
Brian
