### ISSUE TITLE
Don't check for pip or sudo if aws is already present

### ISSUE THREAD

**Issue by DWSR** [CircleCI-Public/aws-cli-orb#13]
### Orb version

`aws-s3@1.0.0`

### What happened

If the `awscli` is already present (i.e. `aws` is in PATH), the `Install AWS CLI` step will still check for the presence of `pip` and `sudo`

### Expected behavior

The step should see that the command is present and exit successfully.

**Comment by iynere** [comment]
@DWSR can you try the latest version of the `s3` orb (1.0.9) & let us know if this is still an issue ?

**Comment by jhoos** [comment]
This is still an issue for us, using the `aws-eks` orb; when you invoke the `install-aws-iam-authenticator` command from that orb, one of the things it does is invoke this orb's `install` command, which blindly tries to install the AWS CLI regardless of whether it's already present in the underlying Docker image. 

The `install` command really should start with something like:

        if which aws > /dev/null; then
          echo "AWS CLI is already installed"
          exit 0
        fi

similar to how https://github.com/CircleCI-Public/aws-eks-orb/blob/master/src/commands/install-aws-iam-authenticator.yml checks for the authenticator already being installed.
