### ISSUE TITLE
request for new release that includes fix for Alpine Linux

### ISSUE THREAD

**Issue by toozej-work** [CircleCI-Public/aws-cli-orb#153]
Hello! Would it be possible to get a new release published that includes the fix for Alpine Linux (https://github.com/CircleCI-Public/aws-cli-orb/pull/138)? This issue is still affecting the latest published release [v4.0.0](https://github.com/CircleCI-Public/aws-cli-orb/releases/tag/v4.0.0)

**Comment by brivu** [comment]
Hey @toozej-work, 

I am working on merging a few more Pull Requests and will cut a new release later this week. 

Thank you! 

Best, 
Brian
