### ISSUE TITLE
Error: unknown command "env" for "circleci"

### ISSUE THREAD

**Issue by SeanHayes** [CircleCI-Public/aws-cli-orb#155]
I just updated to circleci/aws-cli@4.0.0 from version 3. It works fine remotely on circleci, but when I use `circleci local execute my-build` I get this error during "aws-cli/setup":

```
Error: unknown command "env" for "circleci"
Run 'circleci --help' for usage.
ERRO[0000] Exit with status 1 due to generic error       error="unknown command \"env\" for \"circleci\""
Error: 
Exited with code exit status 1

Step failed
```

**Comment by brivu** [comment]
Hey @SeanHayes, 

Can you show me your config so I can see where it's failing? 

Best, 
Brian
