### ISSUE TITLE
4.1.0 includes breaking changes from 4.0.0

### ISSUE THREAD

**Issue by nicolaschambrier** [CircleCI-Public/aws-cli-orb#156]
In 4.1.0 a change has been made which is totally not backward-compatible:

- `aws_access_key_id` used to be an **environment variable name** while it's now expected to be the **value**
- same for `aws_secret_access_key`
- The descriptions for those two parameters did not change, it still says "... _Set this to the name of the environment variable_ ..." which is incorrect

I think this version should be dropped and re-released as `5.0.0` (with updates to the description) as marking this as a minor change could break a lot of workflows, or at least fix the descriptions so that the [public manual](https://circleci.com/developer/orbs/orb/circleci/aws-cli#commands-setup) is correct.

**Comment by brivu** [comment]
Hey @nicolaschambrier, thanks for letting us know. I'm going to get a fix out for this today that should work if you have them stored as environment variables

**Comment by brivu** [comment]
This has been fixed with PR #159. I removed the `$` and changed the way we expand that variable in the script and it works. Please let me know if you encounter something different. Thanks!
