### ISSUE TITLE
aws-cli orb 4.x broken on Server 4.x

### ISSUE THREAD

**Issue by thedoc31** [CircleCI-Public/aws-cli-orb#160]
Server 4.x does not support the `circleci env` commandline parameter yet. Therefore, if you try to import the orb, the build breaks with:

```
Error: unknown command "env" for "circleci"
```

There is no workaround for this as far as I can tell. If this isn't something that can be adapted to also work on Server 4.x, it would be good to prominently note somewhere on the orb doc that it won't work.

**Comment by Almenon** [comment]
I have a similar issue with self-hosted circleci on EKS. `/bin/bash: line 2: circleci: command not found`. 

Relevant: https://circleci.com/docs/runner-faqs/#why-did-my-test-splitting-job-step-error-with-circleci-command-not-found

I fixed it by pointing circleci to circleci-agent in a run step before the aws orb: `sudo ln -s /home/circleci/circleci-agent /usr/local/bin/circleci`. 

Another fix might be to install https://github.com/CircleCI-Public/circleci-cli, as that will internally redirect certain commands to `circleci-agent`, but I didn't test it.

The maintainers could fix this bug by switching from 'circleci' to 'circleci-agent'

**Comment by brivu** [comment]
Hey @thedoc31, I just wanted to let you know that this has been added to the latest version of our server product. Thank you!
