### ISSUE TITLE
The documentation on aws sts assume-role is incorrect / not working in real world scenarios

### ISSUE THREAD

**Issue by queglay** [CircleCI-Public/aws-cli-orb#180]
Following the steps in https://circleci.com/developer/orbs/orb/circleci/aws-cli for configure role, but actually try and use that role in subsequent operations - you will not be able to do it.

aws sts assume-role doesn't persist the log in to the session at all.  the credentials must be used or set to env vars, and this is not occuring when I try to perform operations based on the docs.

See my discussion here:
https://discuss.circleci.com/t/trouble-with-aws-assume-role-with-orb/49774/4

**Comment by brivu** [comment]
Hey @queglay, 

I am going to close this out for now but feel free to reopen if you need anything else! 

Best, 
Brian
