### ISSUE TITLE
Extra hyphen at the end of role_session_name

### ISSUE THREAD

**Issue by m15o** [CircleCI-Public/aws-cli-orb#186]
I am using the assume_role_with_web_identity command, but I have a problem with an extra hyphen (`-`) at the end of role_session_name.

I probably because tr command replaces carriage return emmited by echo command .
```shell
# Remove invalid characters
AWS_CLI_STR_ROLE_SESSION_NAME=$(echo "${AWS_CLI_STR_ROLE_SESSION_NAME}" | tr -sC 'A-Za-z0-9=,.@_\-' '-')
```
https://github.com/CircleCI-Public/aws-cli-orb/blob/v4.1.2/src/scripts/assume_role_with_web_identity.sh#L10

**Comment by marboledacci** [comment]
Should be fixed in version https://circleci.com/developer/orbs/orb/circleci/aws-cli?version=4.2.3 with the changes from @lunarxlark
