### ISSUE TITLE
 aws-cli/install step fails using aws-cli@5.0.0 on xcode 15.4.0

### ISSUE THREAD

**Issue by nick-ohhh** [CircleCI-Public/aws-cli-orb#205]
Utilizing the install command as part of the aws-cli orb results in a step failing during jobs. The error seems to be `python setup.py egg_info did not run successfully`, while using python `3.12`.

Manually updating pip from `23.3.2 -> 24.2` does not resolve this issue.

![Screenshot 2024-08-21 at 10 37 04 AM](https://github.com/user-attachments/assets/a96db5cd-5835-4a46-8a36-609aa4b195bc)

**Comment by marboledacci** [comment]
Apparently the installation from source doesn't work when having python 3.12, I have created an issue on aws-cli with more details [here](https://github.com/aws/aws-cli/issues/8878).
For now I will add a feature to install using brew to the orb. If that's not an option on this case, the other alternative is to use python 3.11.
Unfortunately AWS hasn't provided an official way to install the aws-cli on Apple Silicon, so these two are the alternatives.

**Comment by marboledacci** [comment]
The new version https://circleci.com/developer/orbs/orb/circleci/aws-cli?version=5.1.0 has the support for brew installation.

**Comment by marboledacci** [comment]
I'm closing this as the only possible solution for this is the brew installation, aws-cli does not officially support python 3.12.
