### ISSUE TITLE
AWS static credentials used instead of OIDC

### ISSUE THREAD

**Issue by barth12** [CircleCI-Public/aws-cli-orb#209]
Hello,

In the newest version 5.1.1 when the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set (we set via `context`) the static credentials authentication will be used instead of OIDC even though the orb is configured as follows:

```
      - aws-cli/setup:
          role_arn: << parameters.circleci-oidc-aws-role-arn >>
          role_session_name: "prepare_codeartifact_auth_token"
```

We expect OIDC auth to take over (hopefully our expectation is correct).
I think this was mentioned here: https://github.com/CircleCI-Public/aws-cli-orb/pull/201

**Comment by marboledacci** [comment]
Hi @barth12, on the PR you mention I was trying to replicate this problem you have, but it was always using the OIDC auth, no matter if it had environment set or not. Could you give me more details about your environment (executor, other steps you do) so I can replicate it.

**Comment by barth12** [comment]
Sorry for confussion. You are right. This step authenticates correctly via OIDC. It is the next step (which I haven't pasted before) which is failing because it uses static credentials, so it is not using OIDC session established before. 

```
      - aws-cli/setup:
          role_arn: << parameters.circleci-oidc-aws-role-arn >>
          role_session_name: "prepare_codeartifact_auth_token"
          profile_name: "circleci-oidc-profile"
      - run:
          name: "Generate AWS auth token"
          command: |
            CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
              --domain xxx \
              --domain-owner xxx \
              --query authorizationToken \
              --output text)
```

To pass the OIDC auth I had to use `profile_name` param in `aws-cli/setup` step and ref to this in CodeArtifact auth command. It makes sense as basically the auth result is passed to subsequent steps. This was however different in the version 3 of aws-cli orb - it worked without "saving" into profile.  Anyway, that works now and there is no bug in the orb.

**Comment by marboledacci** [comment]
As there is no problem, then I'm closing this issue.
