### ISSUE TITLE
Semantic Versioning: v0.1.16 breaks interface compatibility

### ISSUE THREAD

**Issue by mbklein** [CircleCI-Public/aws-cli-orb#22]
The change from `configure` to `setup` probably should have resulted in more than a point release, because now all my `circleci/aws-cli@0.1` workflows are broken.

It's not a _huge_ deal, and I can fix them easily. I just think it's worth thinking about in future releases.

**Comment by KyleTryon** [comment]
Hello @mbklein Deeply sorry for the trouble caused here. This absolutely should have been a major change. The deployment process was handled by an older automatic release system that we are currently assessing to remove or improve.  To ensure no changes can affect your CircleCI config you can protect yourself by setting the full x.y.z semver but obviously, what you have should be safe and falls squarely on us (me really).

We are currently in the middle of updating our release system to ensure these issues are mitigated in the future.

**Comment by mbklein** [comment]
No worries! It was a quick and easy fix on our end, and I understand that orbs are still new(ish) enough that these things will shake out. Thanks for the response!
