### ISSUE TITLE
Issue https://github.com/CircleCI-Public/circleci-orbs/issues/179 

### ISSUE THREAD

**Issue by jtownson** [CircleCI-Public/aws-cli-orb#28]
The above issue refers to a bug in this orb.

**Comment by jtownson** [comment]
At a guess, ther problem lies with the `which` command here. I think this because if I pre-install the awscli, the orb still attempt to install the awscli (but then that fails for a different reason: a user prompt to overwrite the existing awscli download fails because there is no stdin):
```
  install:
    description: "Install the AWS CLI via Pip if not already installed."
    steps:
      - run:
          name: "Install AWS CLI"
          command: |
            if which aws > /dev/null; then
              echo "The AWS CLI is already installed. Skipping."
              exit 0
            fi
```

**Comment by lokst** [comment]
@jtownson Would you mind sharing a link to the job where you encountered the problem?

**Comment by KyleTryon** [comment]
Outdated. Please re-open if you continue to experience this issue in the current orb version.
