### ISSUE TITLE
Request: support AWS CLI v2

### ISSUE THREAD

**Issue by skaji** [CircleCI-Public/aws-cli-orb#32]
https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/
Now AWS CLI v2 is generally available. It's nice if aws-cli-orb supports AWS CLI v2.

**Comment by lokst** [comment]
@skaji Thank you for reporting this, this is something we'd like to look into.

**Comment by lokst** [comment]
Closing this as `circleci/aws-cli@1.0.0` now supports installation v2 of the CLI
