### ISSUE TITLE
Less not installed

### ISSUE THREAD

**Issue by krvajal** [CircleCI-Public/aws-cli-orb#41]
AWS CLI uses `less` for output for some commands. Sometimes it is not not available. I think we should check for less and it it is not available it should install it.

**Comment by lokst** [comment]
@krvajal Thank you for the suggestion! We will be considering adding that into the orb. (PRs from the community are also welcome)

**Comment by lokst** [comment]
This should now be resolved in `circleci/aws-cli@1.1.0`, which disables paging.
