### ISSUE TITLE
Default executor doesn't exit after receiving an exit code 0

### ISSUE THREAD

**Issue by jlenos-inflight** [CircleCI-Public/aws-cli-orb#42]
### Orb version

1.0.0

### What happened

I was using this orb's "default" executor and when I switched to use v1.0.0 from v0.1.22 of this orb my job just kept running without completing after receiving an exit code 0.

This message was also in the output:
```WARNING: terminal is not fully functional```

### Expected behavior

The job should have exited after receiving an exit code 0.

**Comment by felicianotech** [comment]
Did some testing with running `exit 0` in a step with additional commands in that same step as well as an additional step. In all testing, the behavior was the same. `exit 0` caused the step to complete but not the job. This was tested with the following images:

- `cimg/python:3.8-node` - the current "default" image
- `cimg/python:3.8` - a previous "default" image
- `circleci/python:2.7-stretch` - a previous "default" image
- `circleci/python:3.8-node` - another image

Here's those builds:
- https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/252/workflows/2140658e-bc5e-43bd-a11e-8f94c49e6622/jobs/1052
- https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/253/workflows/99e328bb-9e6b-4f6c-9710-06a62bd98e6e/jobs/1053
- https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/254/workflows/fc63ff13-f275-459b-961f-9327d67f61be/jobs/1054
- https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/255/workflows/15256ad5-0f84-4f8c-83ab-2b512e9ff68e/jobs/1055
- https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/258/workflows/9021b9bc-119f-4121-8c22-5c2e7e4e0f01/jobs/1058


@jlenos-inflight Can you provide links to a build showcasing the before behavior and one showcasing the after? If those projects are private, you can submit this issue in a CircleCI Support ticket and share those build links there.

**Comment by jlenos-inflight** [comment]
Hi felicianotech,

Thank you for your prompt reply.
This did occur in a private project, but I can shed more detail here as to the job.

The job is using the `aws-code-deploy/deploy-bundle` command from the [circleci/aws-code-deploy@1.0.1](https://circleci.com/orbs/registry/orb/circleci/aws-code-deploy) orb. This command outputted `EXITCODE=0` which successfully ended the step using v0.1.22 of this orb but didn't exit the step using v1.0.0 of this orb.

If this doesn't clarify things, I am happy to open a support ticket.

**Comment by whyman** [comment]
Im encountering the same thing :-1: 

Example snippet below:

```orbs:
  aws-cli: circleci/aws-cli@1.0.0
```

```  deploy-lambda:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Package Lambda
          command: zip panda.zip *.py
      - run:
          name: Update Lambda
          command: aws --no-paginate lambda update-function-code --function-name panda --zip-file fileb://panda.zip
          environment:
            TERM: xterm # Stops AWS-CLI complaining because its got a dumb TTY

**Comment by jlenos-inflight** [comment]
I just hit this in a different context (works fine with 0.1.22):

```
    machine:
      image: ubuntu-1604:201903-01
```

```
      - aws-cli/install:
          skip-install-check: true
      - run:
          name: Log into Amazon ECR
          command: |
            aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run:
          name: Retag ECR Docker Image with latest
          command: |
            MANIFEST=$(aws ecr batch-get-image \
              --repository-name << parameters.repository-name >> \
              --image-ids imageTag=<< parameters.image-tag >> \
              --query 'images[].imageManifest' \
              --output text)
            aws ecr put-image \
              --repository-name << parameters.repository-name >> \
              --image-tag latest \
              --image-manifest "$MANIFEST"
```

Might this be related to AWS CLI v2 setup/install?

**Comment by whyman** [comment]
> Just tried setting version = '1' with skip-install-check = true and it succeeded

Same here, v1 and skip install check works.

**Comment by KyleTryon** [comment]
Hello all, 

I believe this issue has been addressed in the latest minor release. The installation logic has been reworked and the edge case testing has been expanded. Please let us know if you continue to experience any issue in the latest release.

https://circleci.com/orbs/registry/orb/circleci/aws-cli
@1.2.0 released
https://github.com/CircleCI-Public/aws-cli-orb/pull/48
