### ISSUE TITLE
Ability to specify `when` for setup and install commands

### ISSUE THREAD

**Issue by gmemstr** [CircleCI-Public/aws-cli-orb#54]
Related: https://github.com/CircleCI-Public/aws-s3-orb/pull/6

Within CircleCI, we can run steps even after the previous command failed using `when`: https://circleci.com/docs/2.0/configuration-reference/#run

This would be helpful for AWS-related actions that would need to be run every time, regardless of failure, to tear down test infrastructure or upload test results.

**Comment by dkarp0** [comment]
This would be incredibly useful for us. We're uploading our build artifacts to s3 as circleci artifacts are only valid for 30 days. This often included test results, so we need them even on fail.

Additionally, there isn't a good workaround that I'm aware of! If you need `when: always` then you essentially cannot use this orb at all

**Comment by brivu** [comment]
@dkarp0, 

Thanks for letting us know.  I'm going to assign myself this task and will look at it as soon as possible.  

Best, 
Brian

**Comment by brivu** [comment]
Closing with https://github.com/CircleCI-Public/aws-s3-orb/pull/6
