### ISSUE TITLE
Lightweight version 

### ISSUE THREAD

**Issue by hc-danieltiziani** [CircleCI-Public/aws-cli-orb#59]
Looking at the file inflated for installing awscli, doesn't it make sense to have a stripped down version, without `docutils`, `examples` and other stuff that is not required to execute awscli?

**Comment by gmemstr** [comment]
@hc-danieltiziani Heya, do you happen to have a link to a resource detailing installing a more minimal version? I agree that keeping the installation small is a huge advantage.

**Comment by hc-danieltiziani** [comment]
Good point, I did already tried to find some alternative, but could not come up with any.
Opened a Feature Request on the official repo, maybe someone will shed a light there:

https://github.com/aws/aws-cli/issues/5725 

Tks @gmemstr

**Comment by hc-danieltiziani** [comment]
There is some comments on the referenced issue, it might come a bundle with no examples (would be less 18mb this way).
But one thing that would optimize this, would maybe using `unzip -qq awscliv2.zip` (one extra quiet option), because I'm seeing the logs of every file inflated (as below), what do you think @gmemstr ?

```
AWS is not installed
Linux 3aa0c02e3506 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 GNU/Linux
Archive:  awscliv2.zip
   creating: aws/
   creating: aws/dist/
  inflating: aws/README.md           
  inflating: aws/install        
...
```

**Comment by gmemstr** [comment]
Closing this as it doesn't appear to be something we can optimize on our end.

@hc-danieltiziani We recently published an update that quiets the unzip command, so we should be all good on that front :)
