### ISSUE TITLE
aws-cli/setup leaves a 'aws' directory in my project folder

### ISSUE THREAD

**Issue by tripper54** [CircleCI-Public/aws-cli-orb#71]
I zip my project up to deploy as a lambda function via the serverless framework. 

After bumping the version of this orb the deploy would fail with AWS saying the payload was too large.

I ran the build with SSH enabled and noticed an 'aws' directory would appear in my project folder after running aws-cli/setup.

If I exclude this directory from the serverless packaging, the build succeeds again.

Is this an install artefact left behind? Should the install not clean up after itself without leaving artefacts in my project directory?

**Comment by princed** [comment]
Same problem, in our case it breaks ESLint checks.
