### ISSUE TITLE
Handle unzip not installed

### ISSUE THREAD

**Issue by brandon-leapyear** [CircleCI-Public/aws-cli-orb#75]
Using the orb in a plain `centos:7` docker image fails.
```
+ case $SYS_ENV_PLATFORM in
+ curl -sSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
+ unzip -q -o awscliv2.zip
/bin/bash: line 40: unzip: command not found
```
It would be nice if the documentation could list the commands required. Or this error should just be expected, and this ticket can be closed

**Comment by brivu** [comment]
The AWS cli is downloaded as a `zip` file and is present in their documentation. We believe that this error message should just be expected.
