### ISSUE TITLE
Unable to use awscli 1.20: Unsupported Python version detected

### ISSUE THREAD

**Issue by lukaszsamson** [CircleCI-Public/aws-cli-orb#83]
When building from image circleci/elixir:1.12-node (which is based of debian buster - current stable)

the step
```
aws-cli/setup:
  version: '1'
```
fails with
```
Unsupported Python version detected: Python 2.7
To continue using this installer you must use Python 3.6 or later.
For more information see the following blog post: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
```
The image has python 2.7 aliased as python and python 3.7 aliased as python3 but apparently the setup script is choosing 2.7

As https://docs.amazonaws.cn/en_us/cli/latest/userguide/install-linux.html states
> Python 2.7 was deprecated by the Python Software Foundation on January 1, 2020. Going forward, customers using the Amazon CLI version 1 should transition to using Python 3, with a minimum of Python 3.6. Python 2.7 support is deprecated for new versions of the Amazon CLI version 1 starting 7/15/2021.

It probably coincides with the recent release of awscli 1.20 (released 7/15/2021)

**Comment by ahasna** [comment]
What Orb Version are you using?

**Comment by lukaszsamson** [comment]
1.4.1, last compatible with awscli 1.x

**Comment by mcatmos** [comment]
Hi, same issue over here! :(

**Comment by justin-cmp** [comment]
this is still affecting us as well :cry:

**Comment by brivu** [comment]
Hey @lukaszsamson, 

Thank you for letting us know about this issue. There are a couple of things here that may help.  

The image you're trying to use has been deprecated.  Since python 2.7 has been deprecated as well, please use the new Elixir image that can be found here: https://circleci.com/developer/images/image/cimg/elixir

Please let us know if that doesn't work.  

Best, 
Brian

**Comment by lukaszsamson** [comment]
@brivu

> The image you're trying to use has been deprecated.

No it is not. Elixir 1.12 is going to receive support updates for some time. Anyway this is irrelevant in that case

> Since python 2.7 has been deprecated as well...

Yes but python 3.x is available in the image and this orb is unable to find it properly.

> Please let us know if that doesn't work.

It's been months since I stopped using this orb.
